apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-hive
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteMany
  local:
    path: /storage/hive
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - minikube
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-presto
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteMany
  local:
    path: /storage/presto
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - minikube
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-superset
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteMany
  local:
    path: /storage/superset
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - minikube