apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pvc-hive
  namespace: hive-metastore
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hive-metastore
  namespace: hive-metastore
  labels:
    app: hive-metastore
spec:
  replicas: 1
  template:
    metadata:
      name: hive-metastore
      labels:
        app: hive-metastore
    spec:
      volumes:
        - name: hive
          persistentVolumeClaim:
            claimName: local-pvc-hive
      containers:
        - name: hive-metastore
          image: keshavaram/hive_metastore:1.2
          volumeMounts:
            - mountPath: /data/hive
              name: hive
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
  selector:
    matchLabels:
      app: hive-metastore
---
apiVersion: v1
kind: Service
metadata:
  name: hive-metastore
  namespace: hive-metastore
spec:
  selector:
    app: hive-metastore
  ports:
    - port: 9083
      name: metastore
  type: NodePort
