apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pvc-presto
  namespace: presto
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: presto
  namespace: presto
  labels:
    app: presto
spec:
  replicas: 1
  template:
    metadata:
      name: presto
      labels:
        app: presto
    spec:
      volumes:
        - name: data-presto
          persistentVolumeClaim:
            claimName: local-pvc-presto
      containers:
        - name: presto
          image: keshavaram/presto:1.3
          volumeMounts:
            - mountPath: /data/presto
              name: data-presto
      restartPolicy: Always
  selector:
    matchLabels:
      app: presto
---
apiVersion: v1
kind: Service
metadata:
  name: presto
  namespace: presto
spec:
  selector:
    app: presto
  ports:
    - port: 8080
      name: console
  type: NodePort
